# Generated by Django 4.2.6 on 2023-10-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSelections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('S', 'Stripe'), ('P', 'PayPal')], help_text='Required', max_length=255, unique=True, verbose_name='name')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Payment selection',
                'verbose_name_plural': 'Payment selections',
            },
        ),
    ]
